export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const ADD_TODO = 'ADD_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const TOGGLEALL_TODO = 'TOGGLEALL_TODO';
export const DESTROY_TODO = 'DESTROY_TODO';
export const DESTROYCOMPLETED_TODO = 'DESTROYCOMPLETED_TODO';

export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_POST = 'FETCH_POST';
